// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ShutterRequestAction: core.serialization.Schema<
    serializers.ShutterRequestAction.Raw,
    AlphaSDK.ShutterRequestAction
> = core.serialization.enum_(["down", "up"]);

export declare namespace ShutterRequestAction {
    export type Raw = "down" | "up";
}
