// This file was auto-generated by Fern from our API Definition.

export const LogsServerRequestLevel = {
    Debug: "debug",
    Info: "info",
    Warn: "warn",
    Error: "error",
} as const;
export type LogsServerRequestLevel = (typeof LogsServerRequestLevel)[keyof typeof LogsServerRequestLevel];
