// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ConnectionRequestReconnecting: core.serialization.Schema<
    serializers.ConnectionRequestReconnecting.Raw,
    AlphaSDK.ConnectionRequestReconnecting
> = core.serialization.enum_(["on", "off"]);

export declare namespace ConnectionRequestReconnecting {
    export type Raw = "on" | "off";
}
