// This file was auto-generated by Fern from our API Definition.

import { ActionsClient } from "./api/resources/actions/client/Client.js";
import { CamerasClient } from "./api/resources/cameras/client/Client.js";
import { LiveViewClient } from "./api/resources/liveView/client/Client.js";
import { PropertiesClient } from "./api/resources/properties/client/Client.js";
import { SdCardClient } from "./api/resources/sdCard/client/Client.js";
import { ServerClient } from "./api/resources/server/client/Client.js";
import { SettingsClient } from "./api/resources/settings/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace AlphaSDKClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AlphaSDKClient {
    protected readonly _options: NormalizedClientOptions<AlphaSDKClient.Options>;
    protected _server: ServerClient | undefined;
    protected _cameras: CamerasClient | undefined;
    protected _properties: PropertiesClient | undefined;
    protected _actions: ActionsClient | undefined;
    protected _liveView: LiveViewClient | undefined;
    protected _sdCard: SdCardClient | undefined;
    protected _settings: SettingsClient | undefined;

    constructor(options: AlphaSDKClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get server(): ServerClient {
        return (this._server ??= new ServerClient(this._options));
    }

    public get cameras(): CamerasClient {
        return (this._cameras ??= new CamerasClient(this._options));
    }

    public get properties(): PropertiesClient {
        return (this._properties ??= new PropertiesClient(this._options));
    }

    public get actions(): ActionsClient {
        return (this._actions ??= new ActionsClient(this._options));
    }

    public get liveView(): LiveViewClient {
        return (this._liveView ??= new LiveViewClient(this._options));
    }

    public get sdCard(): SdCardClient {
        return (this._sdCard ??= new SdCardClient(this._options));
    }

    public get settings(): SettingsClient {
        return (this._settings ??= new SettingsClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
