// This file was auto-generated by Fern from our API Definition.

export const AlphaSDKEnvironment = {
    Default: "http://localhost:8080",
} as const;

export type AlphaSDKEnvironment = typeof AlphaSDKEnvironment.Default;
