// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AsyncOperationResponse: core.serialization.ObjectSchema<
    serializers.AsyncOperationResponse.Raw,
    AlphaSDK.AsyncOperationResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
});

export declare namespace AsyncOperationResponse {
    export interface Raw {
        success: boolean;
        message: string;
    }
}
