// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AvailableValue: core.serialization.ObjectSchema<serializers.AvailableValue.Raw, AlphaSDK.AvailableValue> =
    core.serialization.object({
        value: core.serialization.string(),
        formatted: core.serialization.string(),
    });

export declare namespace AvailableValue {
    export interface Raw {
        value: string;
        formatted: string;
    }
}
