// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BulkAvailableValue } from "./BulkAvailableValue.js";

export const BulkPropertyEntry: core.serialization.ObjectSchema<
    serializers.BulkPropertyEntry.Raw,
    AlphaSDK.BulkPropertyEntry
> = core.serialization.object({
    current_value: core.serialization.number(),
    current_hex_value: core.serialization.string(),
    current_formatted: core.serialization.string(),
    writable: core.serialization.boolean(),
    available_values: core.serialization.list(BulkAvailableValue),
});

export declare namespace BulkPropertyEntry {
    export interface Raw {
        current_value: number;
        current_hex_value: string;
        current_formatted: string;
        writable: boolean;
        available_values: BulkAvailableValue.Raw[];
    }
}
