// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BulkPropertyEntry } from "./BulkPropertyEntry.js";

export const BulkPropertiesData: core.serialization.ObjectSchema<
    serializers.BulkPropertiesData.Raw,
    AlphaSDK.BulkPropertiesData
> = core.serialization.object({
    properties: core.serialization.record(core.serialization.string(), BulkPropertyEntry),
    total_properties: core.serialization.number(),
});

export declare namespace BulkPropertiesData {
    export interface Raw {
        properties: Record<string, BulkPropertyEntry.Raw>;
        total_properties: number;
    }
}
