// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BulkAvailableValue: core.serialization.ObjectSchema<
    serializers.BulkAvailableValue.Raw,
    AlphaSDK.BulkAvailableValue
> = core.serialization.object({
    value: core.serialization.number(),
    hex_value: core.serialization.string(),
    formatted: core.serialization.string(),
});

export declare namespace BulkAvailableValue {
    export interface Raw {
        value: number;
        hex_value: string;
        formatted: string;
    }
}
