// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CameraInfoConnectionType: core.serialization.Schema<
    serializers.CameraInfoConnectionType.Raw,
    AlphaSDK.CameraInfoConnectionType
> = core.serialization.enum_(["USB", "Network"]);

export declare namespace CameraInfoConnectionType {
    export type Raw = "USB" | "Network";
}
