// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraInfoConnectionType } from "./CameraInfoConnectionType.js";

export const CameraInfo: core.serialization.ObjectSchema<serializers.CameraInfo.Raw, AlphaSDK.CameraInfo> =
    core.serialization.object({
        id: core.serialization.string(),
        model: core.serialization.string(),
        connectionType: CameraInfoConnectionType,
        connected: core.serialization.boolean(),
    });

export declare namespace CameraInfo {
    export interface Raw {
        id: string;
        model: string;
        connectionType: CameraInfoConnectionType.Raw;
        connected: boolean;
    }
}
