// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraSummary } from "./CameraSummary.js";

export const CameraResponse: core.serialization.ObjectSchema<serializers.CameraResponse.Raw, AlphaSDK.CameraResponse> =
    core.serialization.object({
        success: core.serialization.boolean(),
        message: core.serialization.string().optional(),
        camera: CameraSummary.optional(),
        data: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace CameraResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        camera?: CameraSummary.Raw | null;
        data?: Record<string, unknown> | null;
    }
}
