// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CameraSummary: core.serialization.ObjectSchema<serializers.CameraSummary.Raw, AlphaSDK.CameraSummary> =
    core.serialization.object({
        connected: core.serialization.boolean().optional(),
        model: core.serialization.string().optional(),
        id: core.serialization.string().optional(),
    });

export declare namespace CameraSummary {
    export interface Raw {
        connected?: boolean | null;
        model?: string | null;
        id?: string | null;
    }
}
