// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraInfo } from "./CameraInfo.js";

export const CameraListResponse: core.serialization.ObjectSchema<
    serializers.CameraListResponse.Raw,
    AlphaSDK.CameraListResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    cameras: core.serialization.list(CameraInfo),
});

export declare namespace CameraListResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        cameras: CameraInfo.Raw[];
    }
}
