// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CompressedDownloadResponseType: core.serialization.Schema<
    serializers.CompressedDownloadResponseType.Raw,
    AlphaSDK.CompressedDownloadResponseType
> = core.serialization.enum_(["thumbnail", "screennail"]);

export declare namespace CompressedDownloadResponseType {
    export type Raw = "thumbnail" | "screennail";
}
