// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CompressedDownloadResponseType } from "./CompressedDownloadResponseType.js";

export const CompressedDownloadResponse: core.serialization.ObjectSchema<
    serializers.CompressedDownloadResponse.Raw,
    AlphaSDK.CompressedDownloadResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    type: CompressedDownloadResponseType.optional(),
});

export declare namespace CompressedDownloadResponse {
    export interface Raw {
        success: boolean;
        message: string;
        type?: CompressedDownloadResponseType.Raw | null;
    }
}
