// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConnectionMode } from "./ConnectionMode.js";

export const ConnectionStatusResponseData: core.serialization.ObjectSchema<
    serializers.ConnectionStatusResponseData.Raw,
    AlphaSDK.ConnectionStatusResponseData
> = core.serialization.object({
    mode: ConnectionMode.optional(),
});

export declare namespace ConnectionStatusResponseData {
    export interface Raw {
        mode?: ConnectionMode.Raw | null;
    }
}
