// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConnectionMode: core.serialization.Schema<serializers.ConnectionMode.Raw, AlphaSDK.ConnectionMode> =
    core.serialization.enum_(["remote", "remote-transfer", "contents"]);

export declare namespace ConnectionMode {
    export type Raw = "remote" | "remote-transfer" | "contents";
}
