// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraSummary } from "./CameraSummary.js";

export const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, AlphaSDK.ErrorResponse> =
    core.serialization.object({
        success: core.serialization.boolean(),
        message: core.serialization.string(),
        camera: CameraSummary.optional(),
    });

export declare namespace ErrorResponse {
    export interface Raw {
        success: boolean;
        message: string;
        camera?: CameraSummary.Raw | null;
    }
}
