// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { BulkPropertiesData } from "./BulkPropertiesData.js";
import { CameraSummary } from "./CameraSummary.js";

export const GetAllPropertiesResponse: core.serialization.ObjectSchema<
    serializers.GetAllPropertiesResponse.Raw,
    AlphaSDK.GetAllPropertiesResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    camera: CameraSummary.optional(),
    data: BulkPropertiesData,
});

export declare namespace GetAllPropertiesResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        camera?: CameraSummary.Raw | null;
        data: BulkPropertiesData.Raw;
    }
}
