// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraSummary } from "./CameraSummary.js";
import { OsdStatus } from "./OsdStatus.js";

export const GetOsdStatusResponse: core.serialization.ObjectSchema<
    serializers.GetOsdStatusResponse.Raw,
    AlphaSDK.GetOsdStatusResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    camera: CameraSummary.optional(),
    data: OsdStatus,
});

export declare namespace GetOsdStatusResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        camera?: CameraSummary.Raw | null;
        data: OsdStatus.Raw;
    }
}
