// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraSummary } from "./CameraSummary.js";
import { PriorityKeyData } from "./PriorityKeyData.js";

export const GetPriorityKeyResponse: core.serialization.ObjectSchema<
    serializers.GetPriorityKeyResponse.Raw,
    AlphaSDK.GetPriorityKeyResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    camera: CameraSummary.optional(),
    data: PriorityKeyData,
});

export declare namespace GetPriorityKeyResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        camera?: CameraSummary.Raw | null;
        data: PriorityKeyData.Raw;
    }
}
