// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CameraSummary } from "./CameraSummary.js";
import { PropertyData } from "./PropertyData.js";

export const GetPropertyResponse: core.serialization.ObjectSchema<
    serializers.GetPropertyResponse.Raw,
    AlphaSDK.GetPropertyResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    camera: CameraSummary.optional(),
    data: PropertyData,
});

export declare namespace GetPropertyResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        camera?: CameraSummary.Raw | null;
        data: PropertyData.Raw;
    }
}
