// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LiveViewStatus: core.serialization.ObjectSchema<serializers.LiveViewStatus.Raw, AlphaSDK.LiveViewStatus> =
    core.serialization.object({
        enabled: core.serialization.boolean().optional(),
        streaming: core.serialization.boolean().optional(),
    });

export declare namespace LiveViewStatus {
    export interface Raw {
        enabled?: boolean | null;
        streaming?: boolean | null;
    }
}
