// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LogEntryLevel: core.serialization.Schema<serializers.LogEntryLevel.Raw, AlphaSDK.LogEntryLevel> =
    core.serialization.enum_(["debug", "info", "warn", "error"]);

export declare namespace LogEntryLevel {
    export type Raw = "debug" | "info" | "warn" | "error";
}
