// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LogEntryLevel } from "./LogEntryLevel.js";

export const LogEntry: core.serialization.ObjectSchema<serializers.LogEntry.Raw, AlphaSDK.LogEntry> =
    core.serialization.object({
        timestamp: core.serialization.date().optional(),
        level: LogEntryLevel.optional(),
        message: core.serialization.string().optional(),
        cameraId: core.serialization.string().optional(),
    });

export declare namespace LogEntry {
    export interface Raw {
        timestamp?: string | null;
        level?: LogEntryLevel.Raw | null;
        message?: string | null;
        cameraId?: string | null;
    }
}
