// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LutImportResponseData } from "./LutImportResponseData.js";

export const LutImportResponse: core.serialization.ObjectSchema<
    serializers.LutImportResponse.Raw,
    AlphaSDK.LutImportResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string(),
    data: LutImportResponseData.optional(),
});

export declare namespace LutImportResponse {
    export interface Raw {
        success: boolean;
        message: string;
        data?: LutImportResponseData.Raw | null;
    }
}
