// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const LutImportResponseData: core.serialization.ObjectSchema<
    serializers.LutImportResponseData.Raw,
    AlphaSDK.LutImportResponseData
> = core.serialization.object({
    slot: core.serialization.number().optional(),
    file: core.serialization.string().optional(),
});

export declare namespace LutImportResponseData {
    export interface Raw {
        slot?: number | null;
        file?: string | null;
    }
}
