// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const OsdStatus: core.serialization.ObjectSchema<serializers.OsdStatus.Raw, AlphaSDK.OsdStatus> =
    core.serialization.object({
        supported: core.serialization.boolean().optional(),
        enabled: core.serialization.boolean().optional(),
    });

export declare namespace OsdStatus {
    export interface Raw {
        supported?: boolean | null;
        enabled?: boolean | null;
    }
}
