// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PriorityKeySetting: core.serialization.Schema<
    serializers.PriorityKeySetting.Raw,
    AlphaSDK.PriorityKeySetting
> = core.serialization.enum_(["pc-remote", "camera-position"]);

export declare namespace PriorityKeySetting {
    export type Raw = "pc-remote" | "camera-position";
}
