// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PriorityKeySetting } from "./PriorityKeySetting.js";

export const PriorityKeyData: core.serialization.ObjectSchema<
    serializers.PriorityKeyData.Raw,
    AlphaSDK.PriorityKeyData
> = core.serialization.object({
    setting: PriorityKeySetting.optional(),
    rawValue: core.serialization.string().optional(),
});

export declare namespace PriorityKeyData {
    export interface Raw {
        setting?: PriorityKeySetting.Raw | null;
        rawValue?: string | null;
    }
}
