// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AvailableValue } from "./AvailableValue.js";

export const PropertyData: core.serialization.ObjectSchema<serializers.PropertyData.Raw, AlphaSDK.PropertyData> =
    core.serialization.object({
        property: core.serialization.string(),
        value: core.serialization.string(),
        formatted: core.serialization.string(),
        writable: core.serialization.boolean(),
        available_values: core.serialization.list(AvailableValue).optional(),
    });

export declare namespace PropertyData {
    export interface Raw {
        property: string;
        value: string;
        formatted: string;
        writable: boolean;
        available_values?: AvailableValue.Raw[] | null;
    }
}
