// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SaveInfoData: core.serialization.ObjectSchema<serializers.SaveInfoData.Raw, AlphaSDK.SaveInfoData> =
    core.serialization.object({
        path: core.serialization.string().optional(),
        prefix: core.serialization.string().optional(),
        startNo: core.serialization.number().optional(),
    });

export declare namespace SaveInfoData {
    export interface Raw {
        path?: string | null;
        prefix?: string | null;
        startNo?: number | null;
    }
}
