// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SdCardFile: core.serialization.ObjectSchema<serializers.SdCardFile.Raw, AlphaSDK.SdCardFile> =
    core.serialization.object({
        content_id: core.serialization.number(),
        file_id: core.serialization.number(),
        file_path: core.serialization.string(),
        file_size: core.serialization.number(),
        width: core.serialization.number().optional(),
        height: core.serialization.number().optional(),
        creation_year: core.serialization.number().optional(),
        creation_month: core.serialization.number().optional(),
        creation_day: core.serialization.number().optional(),
        creation_hour: core.serialization.number().optional(),
        creation_minute: core.serialization.number().optional(),
        creation_second: core.serialization.number().optional(),
    });

export declare namespace SdCardFile {
    export interface Raw {
        content_id: number;
        file_id: number;
        file_path: string;
        file_size: number;
        width?: number | null;
        height?: number | null;
        creation_year?: number | null;
        creation_month?: number | null;
        creation_day?: number | null;
        creation_hour?: number | null;
        creation_minute?: number | null;
        creation_second?: number | null;
    }
}
