// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SdCardDownloadRequest: core.serialization.ObjectSchema<
    serializers.SdCardDownloadRequest.Raw,
    AlphaSDK.SdCardDownloadRequest
> = core.serialization.object({
    save_path: core.serialization.string().optional(),
});

export declare namespace SdCardDownloadRequest {
    export interface Raw {
        save_path?: string | null;
    }
}
