// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { SdCardFile } from "./SdCardFile.js";

export const SdCardFileListResponse: core.serialization.ObjectSchema<
    serializers.SdCardFileListResponse.Raw,
    AlphaSDK.SdCardFileListResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    slot: core.serialization.number(),
    file_count: core.serialization.number(),
    files: core.serialization.list(SdCardFile),
});

export declare namespace SdCardFileListResponse {
    export interface Raw {
        success: boolean;
        slot: number;
        file_count: number;
        files: SdCardFile.Raw[];
    }
}
