// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ServerStatusServerPlatform: core.serialization.Schema<
    serializers.ServerStatusServerPlatform.Raw,
    AlphaSDK.ServerStatusServerPlatform
> = core.serialization.enum_([
    "darwin-arm64",
    "darwin-x64",
    "linux-arm64",
    "linux-arm",
    "linux-x64",
    "win32-x64",
    "unknown",
]);

export declare namespace ServerStatusServerPlatform {
    export type Raw =
        | "darwin-arm64"
        | "darwin-x64"
        | "linux-arm64"
        | "linux-arm"
        | "linux-x64"
        | "win32-x64"
        | "unknown";
}
