// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ServerStatusCameras } from "./ServerStatusCameras.js";
import { ServerStatusServer } from "./ServerStatusServer.js";

export const ServerStatus: core.serialization.ObjectSchema<serializers.ServerStatus.Raw, AlphaSDK.ServerStatus> =
    core.serialization.object({
        success: core.serialization.boolean(),
        server: ServerStatusServer,
        cameras: ServerStatusCameras,
    });

export declare namespace ServerStatus {
    export interface Raw {
        success: boolean;
        server: ServerStatusServer.Raw;
        cameras: ServerStatusCameras.Raw;
    }
}
