// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ServerStatusServerPlatform } from "./ServerStatusServerPlatform.js";

export const ServerStatusServer: core.serialization.ObjectSchema<
    serializers.ServerStatusServer.Raw,
    AlphaSDK.ServerStatusServer
> = core.serialization.object({
    version: core.serialization.string(),
    sdkVersion: core.serialization.string(),
    uptime: core.serialization.number(),
    platform: ServerStatusServerPlatform,
});

export declare namespace ServerStatusServer {
    export interface Raw {
        version: string;
        sdkVersion: string;
        uptime: number;
        platform: ServerStatusServerPlatform.Raw;
    }
}
