// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { LogEntry } from "./LogEntry.js";

export const ServerLogsResponse: core.serialization.ObjectSchema<
    serializers.ServerLogsResponse.Raw,
    AlphaSDK.ServerLogsResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    logs: core.serialization.list(LogEntry),
    total: core.serialization.number().optional(),
});

export declare namespace ServerLogsResponse {
    export interface Raw {
        success: boolean;
        logs: LogEntry.Raw[];
        total?: number | null;
    }
}
