// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ServerStatusCameras: core.serialization.ObjectSchema<
    serializers.ServerStatusCameras.Raw,
    AlphaSDK.ServerStatusCameras
> = core.serialization.object({
    connected: core.serialization.number(),
    discovered: core.serialization.number(),
});

export declare namespace ServerStatusCameras {
    export interface Raw {
        connected: number;
        discovered: number;
    }
}
