// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SettingsFileRequest: core.serialization.ObjectSchema<
    serializers.SettingsFileRequest.Raw,
    AlphaSDK.SettingsFileRequest
> = core.serialization.object({
    filename: core.serialization.string().optional(),
});

export declare namespace SettingsFileRequest {
    export interface Raw {
        filename?: string | null;
    }
}
