// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const SettingsFileListResponse: core.serialization.ObjectSchema<
    serializers.SettingsFileListResponse.Raw,
    AlphaSDK.SettingsFileListResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
    files: core.serialization.list(core.serialization.string()).optional(),
    count: core.serialization.number().optional(),
});

export declare namespace SettingsFileListResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
        files?: string[] | null;
        count?: number | null;
    }
}
