// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ShutdownServerResponse: core.serialization.ObjectSchema<
    serializers.ShutdownServerResponse.Raw,
    AlphaSDK.ShutdownServerResponse
> = core.serialization.object({
    success: core.serialization.boolean(),
    message: core.serialization.string().optional(),
});

export declare namespace ShutdownServerResponse {
    export interface Raw {
        success: boolean;
        message?: string | null;
    }
}
