// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ZoomDirectionalRequestSpeed: core.serialization.Schema<
    serializers.ZoomDirectionalRequestSpeed.Raw,
    AlphaSDK.ZoomDirectionalRequestSpeed
> = core.serialization.enum_(["normal", "fast"]);

export declare namespace ZoomDirectionalRequestSpeed {
    export type Raw = "normal" | "fast";
}
