// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ZoomDirectionalRequestDirection: core.serialization.Schema<
    serializers.ZoomDirectionalRequestDirection.Raw,
    AlphaSDK.ZoomDirectionalRequestDirection
> = core.serialization.enum_(["in", "out"]);

export declare namespace ZoomDirectionalRequestDirection {
    export type Raw = "in" | "out";
}
