// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ZoomDirectionalRequestDirection } from "./ZoomDirectionalRequestDirection.js";
import { ZoomDirectionalRequestSpeed } from "./ZoomDirectionalRequestSpeed.js";

export const ZoomDirectionalRequest: core.serialization.ObjectSchema<
    serializers.ZoomDirectionalRequest.Raw,
    AlphaSDK.ZoomDirectionalRequest
> = core.serialization.object({
    direction: ZoomDirectionalRequestDirection,
    speed: ZoomDirectionalRequestSpeed,
});

export declare namespace ZoomDirectionalRequest {
    export interface Raw {
        direction: ZoomDirectionalRequestDirection.Raw;
        speed: ZoomDirectionalRequestSpeed.Raw;
    }
}
