// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ZoomSignedSpeedRequest: core.serialization.ObjectSchema<
    serializers.ZoomSignedSpeedRequest.Raw,
    AlphaSDK.ZoomSignedSpeedRequest
> = core.serialization.object({
    speed: core.serialization.number(),
});

export declare namespace ZoomSignedSpeedRequest {
    export interface Raw {
        speed: number;
    }
}
