// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ZoomDirectionalRequest } from "./ZoomDirectionalRequest.js";
import { ZoomSignedSpeedRequest } from "./ZoomSignedSpeedRequest.js";

export const ZoomRequest: core.serialization.Schema<serializers.ZoomRequest.Raw, AlphaSDK.ZoomRequest> =
    core.serialization.undiscriminatedUnion([ZoomDirectionalRequest, ZoomSignedSpeedRequest]);

export declare namespace ZoomRequest {
    export type Raw = ZoomDirectionalRequest.Raw | ZoomSignedSpeedRequest.Raw;
}
