// This file was auto-generated by Fern from our API Definition.

/**
 * Generic envelope for async operations that have been accepted but not yet completed.
 * Watch for the corresponding SSE event (`downloadComplete`, `transferProgress`) to
 * learn when the operation finishes.
 */
export interface AsyncOperationResponse {
    success: boolean;
    message: string;
}
