// This file was auto-generated by Fern from our API Definition.

/**
 * Single entry inside the `available_values` array returned by single-GET
 * property responses. Contains only the hex value (as a string) and the
 * formatted label — no separate numeric value field. The bulk endpoint
 * uses `BulkAvailableValue`, which is a different shape.
 */
export interface AvailableValue {
    /** Hex value to use in SET requests */
    value: string;
    /** Human-readable label */
    formatted: string;
}
