// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Wrapper object inside the bulk-GET `data` field. The
 * `properties` member is a map of property name → entry.
 */
export interface BulkPropertiesData {
    /** Map of property name (matches `PropertyName`) to its current value entry */
    properties: Record<string, AlphaSDK.BulkPropertyEntry>;
    /** Total number of property entries the camera reported (BEFORE deduplication). */
    total_properties: number;
}
