// This file was auto-generated by Fern from our API Definition.

export interface BulkAvailableValue {
    /**
     * Numeric SDK value. Typed as `number` (rather than `int64`) because
     * some properties emit UInt64-range values on the wire that don't fit
     * in a signed 64-bit integer. Treat this field as opaque — use
     * `hex_value` in SET requests.
     */
    value: number;
    hex_value: string;
    formatted: string;
}
