// This file was auto-generated by Fern from our API Definition.

export const CameraInfoConnectionType = {
    Usb: "USB",
    Network: "Network",
} as const;
export type CameraInfoConnectionType = (typeof CameraInfoConnectionType)[keyof typeof CameraInfoConnectionType];
