// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Camera discovered during enumeration
 */
export interface CameraInfo {
    id: string;
    model: string;
    connectionType: AlphaSDK.CameraInfoConnectionType;
    connected: boolean;
}
