// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface CameraListResponse {
    success: boolean;
    message?: string;
    cameras: AlphaSDK.CameraInfo[];
}
