// This file was auto-generated by Fern from our API Definition.

/**
 * Camera info embedded in API responses
 */
export interface CameraSummary {
    connected?: boolean;
    model?: string;
    id?: string;
}
