// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Generic envelope returned by most camera operations. The shape of
 * `data` varies per endpoint — most operations return an empty or
 * null `data`; operations that return structured data document a
 * specific shape. SDK-generated types can treat `data` as an opaque
 * map for generic endpoints.
 */
export interface CameraResponse {
    success: boolean;
    message?: string;
    camera?: AlphaSDK.CameraSummary;
    data?: Record<string, unknown>;
}
