// This file was auto-generated by Fern from our API Definition.

export const CompressedDownloadResponseType = {
    Thumbnail: "thumbnail",
    Screennail: "screennail",
} as const;
export type CompressedDownloadResponseType =
    (typeof CompressedDownloadResponseType)[keyof typeof CompressedDownloadResponseType];
