// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Response envelope for thumbnail/screennail downloads.
 */
export interface CompressedDownloadResponse {
    success: boolean;
    message: string;
    type?: AlphaSDK.CompressedDownloadResponseType;
}
