// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Response envelope for `GET /api/cameras/{id}/connection`. When the
 * camera is connected, `data.mode` reports the active SDK connection
 * mode (`remote` / `remote-transfer` / `contents`) so clients don't
 * have to remember what they passed at connect time. When the camera
 * is not connected, `data` is omitted.
 */
export interface ConnectionStatusResponse {
    success: boolean;
    message?: string;
    camera?: AlphaSDK.CameraSummary;
    data?: AlphaSDK.ConnectionStatusResponseData;
}
