// This file was auto-generated by Fern from our API Definition.

/**
 * - `remote` — Full control + auto-transfer of captured images to host PC
 * - `remote-transfer` — Full control + explicit SD card file access
 * - `contents` — SD card file access only (no shooting or settings control)
 */
export const ConnectionMode = {
    Remote: "remote",
    RemoteTransfer: "remote-transfer",
    Contents: "contents",
} as const;
export type ConnectionMode = (typeof ConnectionMode)[keyof typeof ConnectionMode];
