// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface GetLiveViewStatusResponse {
    success: boolean;
    message?: string;
    camera?: AlphaSDK.CameraSummary;
    data: AlphaSDK.LiveViewStatus;
}
