// This file was auto-generated by Fern from our API Definition.

export interface LiveViewStatus {
    /** Whether live view is enabled on the camera body. */
    enabled?: boolean;
    /** Whether the server is currently capturing frames. */
    streaming?: boolean;
}
