// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface LogEntry {
    timestamp?: Date;
    level?: AlphaSDK.LogEntryLevel;
    message?: string;
    /** Camera ID if log is camera-specific */
    cameraId?: string;
}
