// This file was auto-generated by Fern from our API Definition.

export const LogEntryLevel = {
    Debug: "debug",
    Info: "info",
    Warn: "warn",
    Error: "error",
} as const;
export type LogEntryLevel = (typeof LogEntryLevel)[keyof typeof LogEntryLevel];
