// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface LutImportResponse {
    success: boolean;
    message: string;
    data?: AlphaSDK.LutImportResponseData;
}
