// This file was auto-generated by Fern from our API Definition.

/**
 * Wire-format note: `supported` and `enabled` are sent as the literal
 * strings `"true"` / `"false"` (the server response envelope serializes
 * `data` as a `string→string` map). Clients must coerce to boolean.
 */
export interface OsdStatus {
    /** Whether the connected camera body supports OSD composite frames. Sent as `"true"` / `"false"` — coerce on the client. */
    supported?: boolean;
    /** Whether OSD mode is currently enabled. Sent as `"true"` / `"false"` — coerce on the client. */
    enabled?: boolean;
}
