// This file was auto-generated by Fern from our API Definition.

/**
 * - `pc-remote` — Server has control (required for remote operation)
 * - `camera-position` — Camera body has control
 */
export const PriorityKeySetting = {
    PcRemote: "pc-remote",
    CameraPosition: "camera-position",
} as const;
export type PriorityKeySetting = (typeof PriorityKeySetting)[keyof typeof PriorityKeySetting];
