// This file was auto-generated by Fern from our API Definition.

/**
 * Canonical REST property names. Mirrors the server's `PROPERTY_MAP`
 * (`webapp/server/src/CameraWebController.cpp`). Use `GET /properties/all`
 * to see the full set with current values, writability, and accepted ranges
 * for the connected camera.
 *
 * Some properties are read-only on every body (status / state fields).
 * Others are read-only depending on shooting mode (e.g. `aperture` is
 * read-only outside Manual / Aperture-priority modes). Always check the
 * `writable` field on a single GET before attempting a SET.
 *
 * ## Property tiers
 *
 * **Core (R/W):** `iso`, `aperture`, `shutter-speed`, `drive-mode`,
 * `white-balance`, `focus-mode`, `exposure-program-mode`,
 * `still-image-store-destination`
 *
 * **Image format:** `file-format`, `image-quality`, `raw-compression`
 *
 * **Focus:** `focus-area`, `focus-distance` (read), `focus-position`,
 * `focus-position-current` (read), `focus-driving-status` (read)
 *
 * **Zoom:** `zoom-distance` (read), `zoom-setting`
 *
 * **Battery / power:** `battery-remain` (read)
 *
 * **Video state / format:** `recording-state` (read), `movie-file-format`,
 * `movie-recording-setting`, `movie-recording-frame-rate`
 *
 * **Thermal / errors:** `overheating-state` (read),
 * `camera-error-caution-status` (read), `system-error-caution-status` (read),
 * `camera-system-error-info` (read)
 *
 * **Media slots:** `media-slot1-status`, `media-slot1-remaining-photos`,
 * `media-slot1-remaining-time`, `media-slot2-status`,
 * `media-slot2-remaining-photos`, `media-slot2-remaining-time` (all read)
 *
 * **Exposure:** `exposure-compensation`, `metering-mode`, `ae-lock`,
 * `exposure-step`
 *
 * **Flash:** `flash-mode`, `flash-compensation`, `wireless-flash`
 *
 * **Shutter / silent:** `shutter-type`, `shutter-mode`, `silent-mode`,
 * `shutter-angle`
 *
 * **Image:** `image-size`, `aspect-ratio`, `color-space`, `dro`, `high-iso-nr`
 *
 * **WB fine-tune:** `awb-lock`, `white-balance-color-temp`
 *
 * **Creative / picture profile:** `creative-look`, `flicker-less-shooting`,
 * `picture-profile`, `pp-lut-base-look`
 *
 * **Audio:** `audio-recording`, `audio-input-master-level`
 *
 * **Timecode:** `timecode-preset`, `timecode-format`, `timecode-run`,
 * `timecode-make`
 *
 * **Stabilization / NR:** `image-stabilization`, `movie-stabilization`,
 * `long-exposure-nr`
 *
 * **CineEI / LUT:** `movie-shooting-mode`, `movie-shooting-mode-color-gamut`,
 * `base-look-import-enable`, `embed-lut-file`, `base-look-value`,
 * `shooting-enable`, `exposure-index`, `base-iso`, `aps-c-s35`
 *
 * **Image ID (MakerNote):** `image-id-string`, `image-id-string-max-length`,
 * `image-id-num`, `image-id-num-setting`
 *
 * **Priority:** `priority-key` (also exposed as `/priority-key` resource)
 */
export const PropertyName = {
    PriorityKey: "priority-key",
    Iso: "iso",
    Aperture: "aperture",
    ShutterSpeed: "shutter-speed",
    DriveMode: "drive-mode",
    WhiteBalance: "white-balance",
    FocusMode: "focus-mode",
    ExposureProgramMode: "exposure-program-mode",
    StillImageStoreDestination: "still-image-store-destination",
    FileFormat: "file-format",
    ImageQuality: "image-quality",
    RawCompression: "raw-compression",
    FocusArea: "focus-area",
    FocusDistance: "focus-distance",
    FocusPosition: "focus-position",
    FocusPositionCurrent: "focus-position-current",
    FocusDrivingStatus: "focus-driving-status",
    ZoomDistance: "zoom-distance",
    ZoomSetting: "zoom-setting",
    BatteryRemain: "battery-remain",
    RecordingState: "recording-state",
    MovieFileFormat: "movie-file-format",
    MovieRecordingSetting: "movie-recording-setting",
    MovieRecordingFrameRate: "movie-recording-frame-rate",
    OverheatingState: "overheating-state",
    CameraErrorCautionStatus: "camera-error-caution-status",
    SystemErrorCautionStatus: "system-error-caution-status",
    CameraSystemErrorInfo: "camera-system-error-info",
    MediaSlot1Status: "media-slot1-status",
    MediaSlot1RemainingPhotos: "media-slot1-remaining-photos",
    MediaSlot1RemainingTime: "media-slot1-remaining-time",
    MediaSlot2Status: "media-slot2-status",
    MediaSlot2RemainingPhotos: "media-slot2-remaining-photos",
    MediaSlot2RemainingTime: "media-slot2-remaining-time",
    ExposureCompensation: "exposure-compensation",
    MeteringMode: "metering-mode",
    AeLock: "ae-lock",
    ExposureStep: "exposure-step",
    FlashMode: "flash-mode",
    FlashCompensation: "flash-compensation",
    WirelessFlash: "wireless-flash",
    ShutterType: "shutter-type",
    ShutterMode: "shutter-mode",
    SilentMode: "silent-mode",
    ShutterAngle: "shutter-angle",
    ImageSize: "image-size",
    AspectRatio: "aspect-ratio",
    ColorSpace: "color-space",
    Dro: "dro",
    HighIsoNr: "high-iso-nr",
    AwbLock: "awb-lock",
    WhiteBalanceColorTemp: "white-balance-color-temp",
    CreativeLook: "creative-look",
    FlickerLessShooting: "flicker-less-shooting",
    PictureProfile: "picture-profile",
    PpLutBaseLook: "pp-lut-base-look",
    AudioRecording: "audio-recording",
    AudioInputMasterLevel: "audio-input-master-level",
    TimecodePreset: "timecode-preset",
    TimecodeFormat: "timecode-format",
    TimecodeRun: "timecode-run",
    TimecodeMake: "timecode-make",
    ImageStabilization: "image-stabilization",
    MovieStabilization: "movie-stabilization",
    LongExposureNr: "long-exposure-nr",
    MovieShootingMode: "movie-shooting-mode",
    MovieShootingModeColorGamut: "movie-shooting-mode-color-gamut",
    BaseLookImportEnable: "base-look-import-enable",
    EmbedLutFile: "embed-lut-file",
    BaseLookValue: "base-look-value",
    ShootingEnable: "shooting-enable",
    ExposureIndex: "exposure-index",
    BaseIso: "base-iso",
    ApsCs35: "aps-c-s35",
    ImageIdString: "image-id-string",
    ImageIdStringMaxLength: "image-id-string-max-length",
    ImageIdNum: "image-id-num",
    ImageIdNumSetting: "image-id-num-setting",
} as const;
export type PropertyName = (typeof PropertyName)[keyof typeof PropertyName];
