// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Single-property GET payload returned under `data` by
 * `GET /api/cameras/{id}/properties/{name}`.
 *
 * ## Wire-format note for SDK implementers
 *
 * The server's response envelope packs `data` as a flat `string→string`
 * map, so `writable` arrives as the literal string `"true"` / `"false"`
 * rather than a JSON boolean. Fern-generated clients should coerce it
 * to a real `boolean` before handing it to consumers. The bulk endpoint
 * (`getAllProperties`) already returns a real boolean — see
 * `BulkPropertyEntry`.
 */
export interface PropertyData {
    /** REST property name (matches `PropertyName` enum) */
    property: string;
    /** Hex-encoded current value (use this in SET requests) */
    value: string;
    /** Human-readable display value (also accepted by SET) */
    formatted: string;
    /** Whether this property is currently writable. */
    writable: boolean;
    /**
     * Values the camera currently accepts. Empty array for properties
     * with no enumerated values (range properties, freeform strings).
     */
    available_values?: AlphaSDK.AvailableValue[];
}
