// This file was auto-generated by Fern from our API Definition.

/**
 * Wire-format note: `startNo` is sent as a decimal string (the GET
 * response packs `data` as a `string→string` map). Clients must coerce
 * to integer. `SaveInfoRequest` accepts a real integer on SET.
 */
export interface SaveInfoData {
    path?: string;
    prefix?: string;
    /** Starting file number. Sent as a decimal string on the wire — coerce on the client. */
    startNo?: number;
}
