// This file was auto-generated by Fern from our API Definition.

export interface SdCardFile {
    /** SDK content handle for use in download requests */
    content_id: number;
    /**
     * SDK file handle. Always `0` in contents-transfer mode (one file per content).
     * Multi-file content (e.g. RAW+JPEG pair) returns separate entries with the
     * same `content_id` and distinct `file_id` values.
     */
    file_id: number;
    file_path: string;
    /** File size in bytes */
    file_size: number;
    /** Image width in pixels (contents-transfer mode only) */
    width?: number;
    /** Image height in pixels (contents-transfer mode only) */
    height?: number;
    creation_year?: number;
    creation_month?: number;
    creation_day?: number;
    creation_hour?: number;
    creation_minute?: number;
    creation_second?: number;
}
