// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface SdCardFileListResponse {
    success: boolean;
    slot: number;
    file_count: number;
    files: AlphaSDK.SdCardFile[];
}
