// This file was auto-generated by Fern from our API Definition.

/**
 * Optional save path override. If omitted, uses the connection-time `SetSaveInfo` path.
 */
export interface SdCardDownloadRequest {
    /** Directory path on host PC to save the file */
    save_path?: string;
}
