// This file was auto-generated by Fern from our API Definition.

export interface ServerStatusCameras {
    /** Number of currently connected cameras */
    connected: number;
    /** Number of discovered (available) cameras */
    discovered: number;
}
