// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface ServerLogsResponse {
    success: boolean;
    logs: AlphaSDK.LogEntry[];
    /** Total buffered log count */
    total?: number;
}
