// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface ServerStatusServer {
    /**
     * Server binary version (hardcoded in `handleApiServerStatus`).
     * Distinct from the OpenAPI spec version in `info.version`.
     */
    version: string;
    /** Sony Camera Remote SDK version embedded at build time */
    sdkVersion: string;
    /** Server uptime in seconds */
    uptime: number;
    /** Host OS platform identifier */
    platform: AlphaSDK.ServerStatusServerPlatform;
}
