// This file was auto-generated by Fern from our API Definition.

/** Host OS platform identifier */
export const ServerStatusServerPlatform = {
    DarwinArm64: "darwin-arm64",
    DarwinX64: "darwin-x64",
    LinuxArm64: "linux-arm64",
    LinuxArm: "linux-arm",
    LinuxX64: "linux-x64",
    Win32X64: "win32-x64",
    Unknown: "unknown",
} as const;
export type ServerStatusServerPlatform = (typeof ServerStatusServerPlatform)[keyof typeof ServerStatusServerPlatform];
