// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

export interface ServerStatus {
    success: boolean;
    server: AlphaSDK.ServerStatusServer;
    cameras: AlphaSDK.ServerStatusCameras;
}
