// This file was auto-generated by Fern from our API Definition.

export const ZoomDirectionalRequestSpeed = {
    Normal: "normal",
    Fast: "fast",
} as const;
export type ZoomDirectionalRequestSpeed =
    (typeof ZoomDirectionalRequestSpeed)[keyof typeof ZoomDirectionalRequestSpeed];
