// This file was auto-generated by Fern from our API Definition.

/**
 * Signed speed in range `-10..+10`. Positive = zoom in, negative =
 * zoom out, magnitude = speed. `0` stops an in-progress zoom.
 */
export interface ZoomSignedSpeedRequest {
    speed: number;
}
