// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Direction + named speed preset.
 */
export interface ZoomDirectionalRequest {
    direction: AlphaSDK.ZoomDirectionalRequestDirection;
    speed: AlphaSDK.ZoomDirectionalRequestSpeed;
}
