// This file was auto-generated by Fern from our API Definition.

export const ZoomDirectionalRequestDirection = {
    In: "in",
    Out: "out",
} as const;
export type ZoomDirectionalRequestDirection =
    (typeof ZoomDirectionalRequestDirection)[keyof typeof ZoomDirectionalRequestDirection];
