// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../index.js";

/**
 * Power zoom command. The server accepts two forms:
 *
 * - **Direction + speed preset** (`ZoomDirectionalRequest`):
 *   `{ "direction": "in" | "out", "speed": "normal" | "fast" }`.
 * - **Signed speed** (`ZoomSignedSpeedRequest`):
 *   `{ "speed": -10..+10 }`. Negative = zoom out, positive = zoom in,
 *   magnitude = speed. `0` stops the zoom.
 *
 * The two forms are disjoint on the `speed` field's JSON type, so
 * generated SDKs may either expose them as an untagged union or
 * surface one method per form (see `x-fern-sdk-method-name` on the
 * endpoint).
 */
export type ZoomRequest = AlphaSDK.ZoomDirectionalRequest | AlphaSDK.ZoomSignedSpeedRequest;
