// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cameraId: "cameraId"
 *     }
 */
export interface GetOsdStatusLiveViewRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
}
