// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ConnectionMode } from "../../../../types/ConnectionMode.js";
import { ConnectionRequestReconnecting } from "../../types/ConnectionRequestReconnecting.js";

export const ConnectionRequest: core.serialization.Schema<
    serializers.ConnectionRequest.Raw,
    Omit<AlphaSDK.ConnectionRequest, "cameraId">
> = core.serialization.object({
    mode: ConnectionMode.optional(),
    username: core.serialization.string().optional(),
    password: core.serialization.string().optional(),
    reconnecting: ConnectionRequestReconnecting.optional(),
});

export declare namespace ConnectionRequest {
    export interface Raw {
        mode?: ConnectionMode.Raw | null;
        username?: string | null;
        password?: string | null;
        reconnecting?: ConnectionRequestReconnecting.Raw | null;
    }
}
