// This file was auto-generated by Fern from our API Definition.

/**
 * For continuous shooting: `down` to start, `up` to stop.
 * Omit for single shot.
 */
export const ShutterRequestAction = {
    Down: "down",
    Up: "up",
} as const;
export type ShutterRequestAction = (typeof ShutterRequestAction)[keyof typeof ShutterRequestAction];
