// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const FocusNearFarRequest: core.serialization.Schema<
    serializers.FocusNearFarRequest.Raw,
    Omit<AlphaSDK.FocusNearFarRequest, "cameraId">
> = core.serialization.object({
    step: core.serialization.number(),
});

export declare namespace FocusNearFarRequest {
    export interface Raw {
        step: number;
    }
}
