// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ShutterRequestAction } from "../../types/ShutterRequestAction.js";

export const ShutterRequest: core.serialization.Schema<
    serializers.ShutterRequest.Raw,
    Omit<AlphaSDK.ShutterRequest, "cameraId">
> = core.serialization.object({
    action: ShutterRequestAction.optional(),
});

export declare namespace ShutterRequest {
    export interface Raw {
        action?: ShutterRequestAction.Raw | null;
    }
}
