// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         step: 1
 *     }
 */
export interface FocusNearFarRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** Negative = near, positive = far. Magnitude controls speed. 0 is invalid. */
    step: number;
}
