// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId"
 *     }
 */
export interface ShutterRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /**
     * For continuous shooting: `down` to start, `up` to stop.
     * Omit for single shot.
     */
    action?: AlphaSDK.ShutterRequestAction;
}
