// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as AlphaSDK from "../../../index.js";

export declare namespace ActionsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Shooting commands and motor control (shutter, zoom, focus)
 */
export class ActionsClient {
    protected readonly _options: NormalizedClientOptions<ActionsClient.Options>;

    constructor(options: ActionsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Single shot (no body or empty body), or continuous shooting with `down`/`up` control.
     * For continuous shooting, set drive mode to a continuous mode first.
     *
     * @param {AlphaSDK.ShutterRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.shutter({
     *         cameraId: "cameraId"
     *     })
     */
    public shutter(
        request: AlphaSDK.ShutterRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__shutter(request, requestOptions));
    }

    private async __shutter(
        request: AlphaSDK.ShutterRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/shutter`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.ShutterRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/shutter",
        );
    }

    /**
     * Half-press the shutter button to lock autofocus. No body required.
     *
     * @param {AlphaSDK.HalfPressActionsRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.halfPress({
     *         cameraId: "cameraId"
     *     })
     */
    public halfPress(
        request: AlphaSDK.HalfPressActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__halfPress(request, requestOptions));
    }

    private async __halfPress(
        request: AlphaSDK.HalfPressActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/half-press`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/half-press",
        );
    }

    /**
     * Autofocus then immediately capture in one operation. No body required.
     *
     * @param {AlphaSDK.AfShutterActionsRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.afShutter({
     *         cameraId: "cameraId"
     *     })
     */
    public afShutter(
        request: AlphaSDK.AfShutterActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__afShutter(request, requestOptions));
    }

    private async __afShutter(
        request: AlphaSDK.AfShutterActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/af-shutter`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/af-shutter",
        );
    }

    /**
     * Control power zoom lenses. Requires a power zoom lens to be attached.
     *
     * @param {AlphaSDK.ZoomActionsRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.zoom({
     *         cameraId: "cameraId",
     *         body: {
     *             direction: "in",
     *             speed: "normal"
     *         }
     *     })
     */
    public zoom(
        request: AlphaSDK.ZoomActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__zoom(request, requestOptions));
    }

    private async __zoom(
        request: AlphaSDK.ZoomActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/zoom`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.ZoomRequest.jsonOrThrow(_body, { unrecognizedObjectKeys: "strip", omitUndefined: true }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/zoom",
        );
    }

    /**
     * Start or stop movie recording. Server tracks the current state via the SDK
     * and toggles it on each call. Camera must be in a movie shooting mode.
     *
     * @param {AlphaSDK.MovieRecActionsRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.movieRec({
     *         cameraId: "cameraId"
     *     })
     */
    public movieRec(
        request: AlphaSDK.MovieRecActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__movieRec(request, requestOptions));
    }

    private async __movieRec(
        request: AlphaSDK.MovieRecActionsRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/movie-rec`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/movie-rec",
        );
    }

    /**
     * Move focus toward near or far in discrete steps.
     * Range: `-7` (near, max speed) to `+7` (far, max speed).
     * Magnitude controls speed. `0` is not valid.
     *
     * @param {AlphaSDK.FocusNearFarRequest} request
     * @param {ActionsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.actions.focusNearFar({
     *         cameraId: "cameraId",
     *         step: 1
     *     })
     */
    public focusNearFar(
        request: AlphaSDK.FocusNearFarRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__focusNearFar(request, requestOptions));
    }

    private async __focusNearFar(
        request: AlphaSDK.FocusNearFarRequest,
        requestOptions?: ActionsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/actions/focus-near-far`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.FocusNearFarRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/actions/focus-near-far",
        );
    }
}
