// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const LutImportRequest: core.serialization.Schema<
    serializers.LutImportRequest.Raw,
    Omit<AlphaSDK.LutImportRequest, "cameraId">
> = core.serialization.object({
    filePath: core.serialization.string(),
    slot: core.serialization.number().optional(),
});

export declare namespace LutImportRequest {
    export interface Raw {
        filePath: string;
        slot?: number | null;
    }
}
