// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const PropertySetRequest: core.serialization.Schema<
    serializers.PropertySetRequest.Raw,
    Omit<AlphaSDK.PropertySetRequest, "cameraId" | "propertyName">
> = core.serialization.object({
    value: core.serialization.string(),
});

export declare namespace PropertySetRequest {
    export interface Raw {
        value: string;
    }
}
