// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { PriorityKeySetting } from "../../../../types/PriorityKeySetting.js";

export const SetPriorityKeyRequest: core.serialization.Schema<
    serializers.SetPriorityKeyRequest.Raw,
    Omit<AlphaSDK.SetPriorityKeyRequest, "cameraId">
> = core.serialization.object({
    setting: PriorityKeySetting,
});

export declare namespace SetPriorityKeyRequest {
    export interface Raw {
        setting: PriorityKeySetting.Raw;
    }
}
