// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         slotNumber: 1,
 *         contentId: 1,
 *         fileId: 1,
 *         body: {}
 *     }
 */
export interface DownloadSdCardRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** SD card slot number (1 or 2) */
    slotNumber: number;
    /** SDK content identifier from `listSDCardFiles` response */
    contentId: number;
    /** SDK file identifier from `listSDCardFiles` response (always `0` in contents-transfer mode) */
    fileId: number;
    body: AlphaSDK.SdCardDownloadRequest;
}
