// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         slotNumber: 1
 *     }
 */
export interface ListSdCardRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** SD card slot number (1 or 2) */
    slotNumber: number;
}
