// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId"
 *     }
 */
export interface ConnectionRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    mode?: AlphaSDK.ConnectionMode;
    /** For network cameras */
    username?: string;
    /** For network cameras */
    password?: string;
    /** Auto-reconnect on disconnection */
    reconnecting?: AlphaSDK.ConnectionRequestReconnecting;
}
