// This file was auto-generated by Fern from our API Definition.

/** Auto-reconnect on disconnection */
export const ConnectionRequestReconnecting = {
    On: "on",
    Off: "off",
} as const;
export type ConnectionRequestReconnecting =
    (typeof ConnectionRequestReconnecting)[keyof typeof ConnectionRequestReconnecting];
