// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface LogsServerRequest {
    /** Number of recent log lines to return (default 100) */
    lines?: number;
    /** Minimum log level filter */
    level?: AlphaSDK.LogsServerRequestLevel;
}
