// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as AlphaSDK from "../../../index.js";

export declare namespace SettingsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Save path configuration and camera settings file management
 */
export class SettingsClient {
    protected readonly _options: NormalizedClientOptions<SettingsClient.Options>;

    constructor(options: SettingsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Returns the current save directory, filename prefix, and start number for auto-transferred images.
     *
     * @param {AlphaSDK.GetSaveInfoSettingsRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.getSaveInfo({
     *         cameraId: "cameraId"
     *     })
     */
    public getSaveInfo(
        request: AlphaSDK.GetSaveInfoSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.GetSaveInfoResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSaveInfo(request, requestOptions));
    }

    private async __getSaveInfo(
        request: AlphaSDK.GetSaveInfoSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.GetSaveInfoResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/settings/save-info`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetSaveInfoResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/settings/save-info",
        );
    }

    /**
     * Configure the save directory, filename prefix, and start number.
     *
     * @param {AlphaSDK.SaveInfoRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.setSaveInfo({
     *         cameraId: "cameraId"
     *     })
     */
    public setSaveInfo(
        request: AlphaSDK.SaveInfoRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__setSaveInfo(request, requestOptions));
    }

    private async __setSaveInfo(
        request: AlphaSDK.SaveInfoRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/settings/save-info`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.SaveInfoRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PUT",
            "/api/cameras/{cameraId}/settings/save-info",
        );
    }

    /**
     * Download the camera's current settings to a file on the host PC.
     *
     * @param {AlphaSDK.DownloadSettingsRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.download({
     *         cameraId: "cameraId",
     *         body: {}
     *     })
     */
    public download(
        request: AlphaSDK.DownloadSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__download(request, requestOptions));
    }

    private async __download(
        request: AlphaSDK.DownloadSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/settings/download`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.SettingsFileRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/settings/download",
        );
    }

    /**
     * Upload a previously saved settings file back to the camera.
     *
     * @param {AlphaSDK.UploadSettingsRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.upload({
     *         cameraId: "cameraId",
     *         body: {}
     *     })
     */
    public upload(
        request: AlphaSDK.UploadSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__upload(request, requestOptions));
    }

    private async __upload(
        request: AlphaSDK.UploadSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/settings/upload`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.SettingsFileRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/settings/upload",
        );
    }

    /**
     * Lists camera settings files (`*.DAT`) previously saved to the host PC via `downloadCameraSettings`.
     *
     * @param {AlphaSDK.ListFilesSettingsRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.listFiles({
     *         cameraId: "cameraId"
     *     })
     */
    public listFiles(
        request: AlphaSDK.ListFilesSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.SettingsFileListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listFiles(request, requestOptions));
    }

    private async __listFiles(
        request: AlphaSDK.ListFilesSettingsRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.SettingsFileListResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/settings/files`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.SettingsFileListResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/settings/files",
        );
    }

    /**
     * Initiates an async import of a `.cube` LUT file from the host filesystem
     * into one of the camera's user LUT slots (1–16). CineEI / cinema bodies only.
     *
     * @param {AlphaSDK.LutImportRequest} request
     * @param {SettingsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.settings.importLut({
     *         cameraId: "cameraId",
     *         filePath: "/Users/me/luts/example.cube"
     *     })
     */
    public importLut(
        request: AlphaSDK.LutImportRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.LutImportResponse> {
        return core.HttpResponsePromise.fromPromise(this.__importLut(request, requestOptions));
    }

    private async __importLut(
        request: AlphaSDK.LutImportRequest,
        requestOptions?: SettingsClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.LutImportResponse>> {
        const { cameraId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/lut/import`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            requestType: "json",
            body: serializers.LutImportRequest.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.LutImportResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/lut/import",
        );
    }
}
