// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as serializers from "../../../../serialization/index.js";
import * as AlphaSDK from "../../../index.js";

export declare namespace LiveViewClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Live view streaming and OSD overlay control
 */
export class LiveViewClient {
    protected readonly _options: NormalizedClientOptions<LiveViewClient.Options>;

    constructor(options: LiveViewClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Sends the SDK `Setting_Key_EnableLiveView` command to the camera.
     *
     * @param {AlphaSDK.EnableLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.enable({
     *         cameraId: "cameraId"
     *     })
     */
    public enable(
        request: AlphaSDK.EnableLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__enable(request, requestOptions));
    }

    private async __enable(
        request: AlphaSDK.EnableLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/enable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/enable",
        );
    }

    /**
     * Sends the SDK `Setting_Key_DisableLiveView` command. Stops live view streaming if it was running.
     *
     * @param {AlphaSDK.DisableLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.disable({
     *         cameraId: "cameraId"
     *     })
     */
    public disable(
        request: AlphaSDK.DisableLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__disable(request, requestOptions));
    }

    private async __disable(
        request: AlphaSDK.DisableLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/disable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/disable",
        );
    }

    /**
     * Returns whether live view is `enabled` (camera setting) and whether
     * the server is currently `streaming` frames from the camera.
     *
     * @param {AlphaSDK.GetStatusLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.getStatus({
     *         cameraId: "cameraId"
     *     })
     */
    public getStatus(
        request: AlphaSDK.GetStatusLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.GetLiveViewStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getStatus(request, requestOptions));
    }

    private async __getStatus(
        request: AlphaSDK.GetStatusLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.GetLiveViewStatusResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/status`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetLiveViewStatusResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/live-view/status",
        );
    }

    /**
     * Starts the frame capture worker thread. Auto-enables live view if disabled.
     *
     * @param {AlphaSDK.StartLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.start({
     *         cameraId: "cameraId"
     *     })
     */
    public start(
        request: AlphaSDK.StartLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__start(request, requestOptions));
    }

    private async __start(
        request: AlphaSDK.StartLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/start`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/start",
        );
    }

    /**
     * Stops the frame capture worker thread. Live view itself remains enabled on the camera unless you also call `disableLiveView`.
     *
     * @param {AlphaSDK.StopLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.stop({
     *         cameraId: "cameraId"
     *     })
     */
    public stop(
        request: AlphaSDK.StopLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__stop(request, requestOptions));
    }

    private async __stop(
        request: AlphaSDK.StopLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/stop`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/stop",
        );
    }

    /**
     * Returns the latest live view frame as a JPEG image. Streaming must be
     * started first via `liveView.start`. Poll this endpoint at ~15 fps
     * (every ~66 ms) to render a live preview.
     *
     * @throws {@link AlphaSDK.NotFoundError}
     */
    public getFrame(
        request: AlphaSDK.GetFrameLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getFrame(request, requestOptions));
    }

    private async __getFrame(
        request: AlphaSDK.GetFrameLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/frame`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AlphaSDK.NotFoundError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/live-view/frame",
        );
    }

    /**
     * Enable On-Screen Display overlay via `CrDeviceProperty_OSDImageMode`.
     *
     * @param {AlphaSDK.EnableOsdLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.enableOsd({
     *         cameraId: "cameraId"
     *     })
     */
    public enableOsd(
        request: AlphaSDK.EnableOsdLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__enableOsd(request, requestOptions));
    }

    private async __enableOsd(
        request: AlphaSDK.EnableOsdLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/osd-enable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/osd-enable",
        );
    }

    /**
     * Disables the camera's OSD overlay. Subsequent live view frames will not include UI overlays.
     *
     * @param {AlphaSDK.DisableOsdLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.disableOsd({
     *         cameraId: "cameraId"
     *     })
     */
    public disableOsd(
        request: AlphaSDK.DisableOsdLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.CameraResponse> {
        return core.HttpResponsePromise.fromPromise(this.__disableOsd(request, requestOptions));
    }

    private async __disableOsd(
        request: AlphaSDK.DisableOsdLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.CameraResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/osd-disable`,
            ),
            method: "POST",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.CameraResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/cameras/{cameraId}/live-view/osd-disable",
        );
    }

    /**
     * Returns whether OSD is `supported` on this camera body and whether it is currently `enabled`.
     *
     * @param {AlphaSDK.GetOsdStatusLiveViewRequest} request
     * @param {LiveViewClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link AlphaSDK.BadRequestError}
     *
     * @example
     *     await client.liveView.getOsdStatus({
     *         cameraId: "cameraId"
     *     })
     */
    public getOsdStatus(
        request: AlphaSDK.GetOsdStatusLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<AlphaSDK.GetOsdStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getOsdStatus(request, requestOptions));
    }

    private async __getOsdStatus(
        request: AlphaSDK.GetOsdStatusLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<AlphaSDK.GetOsdStatusResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/osd-status`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: serializers.GetOsdStatusResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new AlphaSDK.BadRequestError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/live-view/osd-status",
        );
    }

    /**
     * Returns a composited JPEG with live view image + camera UI overlay.
     * Same polling pattern as `liveView.getFrame` — OSD must be enabled
     * first via `liveView.enableOSD`.
     *
     * @throws {@link AlphaSDK.NotFoundError}
     */
    public getOsdFrame(
        request: AlphaSDK.GetOsdFrameLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): core.HttpResponsePromise<core.BinaryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getOsdFrame(request, requestOptions));
    }

    private async __getOsdFrame(
        request: AlphaSDK.GetOsdFrameLiveViewRequest,
        requestOptions?: LiveViewClient.RequestOptions,
    ): Promise<core.WithRawResponse<core.BinaryResponse>> {
        const { cameraId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher<core.BinaryResponse>({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AlphaSDKEnvironment.Default,
                `api/cameras/${core.url.encodePathParam(cameraId)}/live-view/osd-frame`,
            ),
            method: "GET",
            headers: _headers,
            queryString: core.url.queryBuilder().mergeAdditional(requestOptions?.queryParams).build(),
            responseType: "binary-response",
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new AlphaSDK.NotFoundError(
                        serializers.ErrorResponse.parseOrThrow(_response.error.body, {
                            unrecognizedObjectKeys: "passthrough",
                            allowUnrecognizedUnionMembers: true,
                            allowUnrecognizedEnumValues: true,
                            skipValidation: true,
                            breadcrumbsPrefix: ["response"],
                        }),
                        _response.rawResponse,
                    );
                default:
                    throw new errors.AlphaSDKError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/cameras/{cameraId}/live-view/osd-frame",
        );
    }
}
