// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         filePath: "/Users/me/luts/example.cube"
 *     }
 */
export interface LutImportRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** Absolute or working-directory-relative path to a `.cube` file on the host */
    filePath: string;
    /** Camera user LUT slot to import into */
    slot?: number;
}
