// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         cameraId: "cameraId"
 *     }
 */
export interface SaveInfoRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** Directory path on host PC */
    path?: string;
    /** Filename prefix */
    prefix?: string;
    /** Starting file number */
    startNo?: number;
}
