// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         body: {}
 *     }
 */
export interface UploadSettingsRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    body: AlphaSDK.SettingsFileRequest;
}
