// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         propertyName: "priority-key",
 *         value: "value"
 *     }
 */
export interface PropertySetRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    /** Property name */
    propertyName: AlphaSDK.PropertyName;
    /**
     * Hex value from `available_values` (e.g. `"0x1007d"`), human-readable
     * string (e.g. `"1/125"`, `"f/5.6"`, `"wide"`), or decimal string.
     */
    value: string;
}
