// This file was auto-generated by Fern from our API Definition.

import type * as AlphaSDK from "../../../../index.js";

/**
 * @example
 *     {
 *         cameraId: "cameraId",
 *         setting: "pc-remote"
 *     }
 */
export interface SetPriorityKeyRequest {
    /** Camera identifier (e.g. `D10F60149B0C`) */
    cameraId: string;
    setting: AlphaSDK.PriorityKeySetting;
}
